import React, {Component} from 'react'
import ReactCSSTransitionGroup from 'react-addons-css-transition-group'
import autobind from 'autobind-decorator'
import immutable from 'immutable'
import TextMessage from './TextMessage.jsx'
import ImageMessage from './ImageMessage.jsx'
import FileMessage from './FileMessage.jsx'
import messageMiddle from '../middlewares/message.js'
import SignOwl from './SignOwl.jsx'
import Loading from './Loading.jsx'
import language from '../config/language.js'
import fiora from '../middlewares/fiora.js'
import {loadRoomHistory, errPrint} from '../actions/combin.js'
import {setMenuState} from '../actions/pageUI.js'
import scroll from '../util/scroll.js'

import '../less/MessageContainer.less'